### ISSUE TITLE
QlformHelper::$captchaToBeUsed of type int

### ISSUE THREAD

**Issue by WvdMersch** [hoochicken/mod_qlform#2]
I have a problem with the latest version v11.1.1. I in Joomla 4.2.3. I get the following error:

Cannot assign string to property Joomla\Module\Qlform\Site\Helper\QlformHelper::$captchaToBeUsed of type int

The website link is: https://www.alphenskozakkenkoor.nl/contact/contactformulier

**Comment by hoochicken** [comment]
This issue has been solved with following Release: https://github.com/hoochicken/mod_qlform/releases/tag/v11.2.1
