### ISSUE TITLE
The check of Joomla version is not correct

### ISSUE THREAD

**Issue by patatagit** [hoochicken/mod_qlform#6]
Hi,
on joomla 3 installation this check is true but it should be false
modules/mod_qlform/helper/QlformHelper.php line 934
`if (4 >= (int) JVERSION) {`

Please, change the operator from ">=" to "<="
`if (4 <= (int) JVERSION) {`

Thanks

**Comment by hoochicken** [comment]
I guess I was drunk when commiting THAT :-D

**Comment by hoochicken** [comment]
Check out the new release 11.3.0 
https://github.com/hoochicken/mod_qlform/releases/tag/v11.3.0

**Comment by hoochicken** [comment]
Rhanks for taking time to popint out the mistake, GREAT!

**Comment by patatagit** [comment]
:-D
Thanks to you! I love this module!

**Comment by hoochicken** [comment]
Thank you, little messages like yours make a developer remember, why she spends so much time on a seemingly pointless creation. For it is not pointless anymore, but now the creation gains meaning and purpose, thanks:-)
